In [25]:
import numpy as np
from sklearn import linear_model
import pandas as pd
data = np.loadtxt('01_heights_weights_genders.csv', delimiter=',', skiprows=1)

In [ ]:
data = np.loadtxt('01_heights_weights_genders.csv', delimiter=',', skiprows=1)

In [18]:
data

array([[  1.        ,  73.84701702, 241.89356318],
       [  1.        ,  68.78190405, 162.31047252],
       [  1.        ,  74.11010539, 212.74085556],
       ...,
       [  0.        ,  63.86799221, 128.47531878],
       [  0.        ,  69.03424313, 163.85246135],
       [  0.        ,  61.94424588, 113.64910268]])

In [30]:
X = data[:,1:]
y = data[:,0]

In [31]:
y

array([1., 1., 1., ..., 0., 0., 0.])

In [32]:
clf = linear_model.LogisticRegression(C = 1e40,solver = 'newton-cg')
fitted_model = clf.fit(X,y)

In [38]:
prediction_result=clf.predict([(70,180)])

In [39]:
prediction_result

array([1.])

In [45]:
print(fitted_model.intercept_,fitted_model.coef_, sep = '\n')

[0.69254178]
[[-0.49261999  0.19834042]]


In [44]:
help('print')

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

