In [4]:
import numpy as np

In [5]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [6]:
from sklearn import svm
clf = svm.SVC(gamma = 0.001, C=100)

In [7]:
clf.fit(digits.data[:-1],digits.target[:-1])
clf.predict(digits.data[-1:])

array([8])

In [8]:
rng =np.random.RandomState(0)
x = rng.rand(10,2000)
x=np.array(x, dtype='float32')

In [9]:
from sklearn import random_projection
transformer=random_projection.GaussianRandomProjection()
x_new=transformer.fit_transform(x)
x_new.dtype

dtype('float64')

Preprocess - Standartize

In [10]:
from sklearn import preprocessing
X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])

In [11]:
scaler=preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler()

In [12]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [13]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [14]:
X_scaled=scaler.transform(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [15]:
X_scaled.mean(axis=0)
X_scaled.std(axis=0)

array([1., 1., 1.])

In [16]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [17]:
X,y = make_classification(random_state=42)
X_train,X_test,y_train,y_test = train_test_split(X,y, random_state=42)
pipe= make_pipeline(StandardScaler(), LogisticRegression())
display(pipe.fit(X_train, y_train))

pipe.score(X_test, y_test)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

0.96

In [18]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_train_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [19]:
X_test=np.array([[-3.,-1.,4.]])
X_test_minmax=min_max_scaler.transform(X_test)
X_test_minmax
print(min_max_scaler.scale_)
print(min_max_scaler.min_)

[0.5        0.5        0.33333333]
[0.         0.5        0.33333333]


In [20]:
X,y = datasets.load_iris(return_X_y = True)
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=0)
quantile_transformer = preprocessing.QuantileTransformer(random_state = 0)
X_train_trans = quantile_transformer.fit_transform(X_train)
X_test_trans = quantile_transformer.transform(X_test)
np.percentile(X_train[:,0], [0,25,50,75,100])

/usr/lib/python3.9/site-packages/sklearn/preprocessing/_data.py:2612: UserWarning: n_quantiles (1000) is greater than the total number of samples (112). n_quantiles is set to n_samples.
  warnings.warn("n_quantiles (%s) is greater than the total number "


array([4.3, 5.1, 5.8, 6.5, 7.9])

In [21]:
np.percentile(X_train_trans[:,0],[0,25,50,75,100])

array([0.        , 0.23873874, 0.50900901, 0.74324324, 1.        ])

In [22]:
np.percentile(X_test[:, 0], [0, 25, 50, 75, 100])

array([4.4  , 5.125, 5.75 , 6.175, 7.3  ])

In [23]:
np.percentile(X_test_trans[:, 0], [0, 25, 50, 75, 100])

array([0.01351351, 0.25      , 0.47747748, 0.60472973, 0.94144144])

In [24]:
pt = preprocessing.PowerTransformer(method="box-cox", standardize=False)
X_lognormal = np.random.RandomState(616).lognormal(size=(3,3))
X_lognormal

array([[1.28331718, 1.18092228, 0.84160269],
       [0.94293279, 1.60960836, 0.3879099 ],
       [1.35235668, 0.21715673, 1.09977091]])

In [25]:
pt.fit_transform(X_lognormal)

array([[ 0.49024349,  0.17881995, -0.1563781 ],
       [-0.05102892,  0.58863195, -0.57612415],
       [ 0.69420009, -0.84857822,  0.10051454]])

In [26]:
qunatlie_transformer=preprocessing.QuantileTransformer(output_distribution='normal',random_state = 0)
X_trans = quantile_transformer.fit_transform(X)
quantile_transformer.quantiles_

/usr/lib/python3.9/site-packages/sklearn/preprocessing/_data.py:2612: UserWarning: n_quantiles (1000) is greater than the total number of samples (150). n_quantiles is set to n_samples.
  warnings.warn("n_quantiles (%s) is greater than the total number "


array([[4.3, 2. , 1. , 0.1],
       [4.4, 2.2, 1.1, 0.1],
       [4.4, 2.2, 1.2, 0.1],
       [4.4, 2.2, 1.2, 0.1],
       [4.5, 2.3, 1.3, 0.1],
       [4.6, 2.3, 1.3, 0.2],
       [4.6, 2.3, 1.3, 0.2],
       [4.6, 2.3, 1.3, 0.2],
       [4.6, 2.4, 1.3, 0.2],
       [4.7, 2.4, 1.3, 0.2],
       [4.7, 2.4, 1.3, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [5. , 2.6, 1.4, 0.2],
       [5. , 2.6, 1.4, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5.1, 2.7, 1.5, 0.2],
       [5.1, 2.8, 1.5, 0.2],
       [5.1, 2

In [27]:
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized    

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [28]:
normalizer = preprocessing.Normalizer().fit(X)
normalizer

Normalizer()

In [29]:
normalizer.transform([[-1.,1.,0.]])

array([[-0.70710678,  0.70710678,  0.        ]])

# Encoding categorical values

In [30]:
enc = preprocessing.OrdinalEncoder()
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)

OrdinalEncoder()

In [31]:
enc.transform([['female', 'from US', 'uses Safari']])

array([[0., 1., 1.]])

In [32]:
genders = ['female', 'male']
locations = ['from Africa', 'from Asia', 'from Europe', 'from US']
browsers = ['uses Chrome', 'uses Firefox', 'uses IE', 'uses Safari']
enc=preprocessing.OneHotEncoder(categories=[genders,locations,browsers])
enc.fit(X)

OneHotEncoder(categories=[['female', 'male'],
                          ['from Africa', 'from Asia', 'from Europe',
                           'from US'],
                          ['uses Chrome', 'uses Firefox', 'uses IE',
                           'uses Safari']])

In [33]:
enc.transform([['female', 'from Asia', 'uses Chrome']]).toarray()

array([[1., 0., 0., 1., 0., 0., 1., 0., 0., 0.]])

In [34]:
enc2=preprocessing.OneHotEncoder(handle_unknown='ignore')
enc2.fit(X)
enc2.transform([['female', 'from Asia', 'uses Chrome']]).toarray()


array([[1., 0., 0., 0., 0., 0.]])

In [35]:
X = [['male', 'US', 'Safari'],
     ['female', 'Europe', 'Firefox'],
     ['female', 'Asia', 'Chrome']]
drop_enc=preprocessing.OneHotEncoder(drop='if_binary').fit(X)
drop_enc.categories_

[array(['female', 'male'], dtype=object),
 array(['Asia', 'Europe', 'US'], dtype=object),
 array(['Chrome', 'Firefox', 'Safari'], dtype=object)]

In [36]:
drop_enc.transform(X).toarray()

array([[1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 0.]])

# Discretization

In [37]:
X = np.array([[ -3., 5., 15 ],
              [  0., 6., 14 ],
              [  6., 3., 11 ]])
est = preprocessing.KBinsDiscretizer(n_bins=[3,2,2], encode='ordinal').fit(X)

In [38]:
est.transform(X)

array([[0., 1., 1.],
       [1., 1., 1.],
       [2., 0., 0.]])

# Generating polynomial features

In [39]:
from sklearn.preprocessing import PolynomialFeatures
X=np.arange(6).reshape(3,2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
poly=PolynomialFeatures(2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [43]:
X = np.arange(9).reshape(3,3)
print(X)
poly=PolynomialFeatures(degree = 3, interaction_only=False)
poly.fit_transform(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[  1.,   0.,   1.,   2.,   0.,   0.,   0.,   1.,   2.,   4.,   0.,
          0.,   0.,   0.,   0.,   0.,   1.,   2.,   4.,   8.],
       [  1.,   3.,   4.,   5.,   9.,  12.,  15.,  16.,  20.,  25.,  27.,
         36.,  45.,  48.,  60.,  75.,  64.,  80., 100., 125.],
       [  1.,   6.,   7.,   8.,  36.,  42.,  48.,  49.,  56.,  64., 216.,
        252., 288., 294., 336., 384., 343., 392., 448., 512.]])

In [48]:
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.log1p, check_inverse = True,validate = True)
X = np.array([[0,1],[2,3]])
transformer.fit(X)
transformer.transform(X)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [47]:
import warnings

warnings.filterwarnings("error", message=".*check_inverse*", category = UserWarning, append=False)